In [2]:
import numpy as np

In [2]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.linspace(1, 4, 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [5]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
x[1:7:2]

array([1, 3, 5])

In [8]:
x[-2:10]

array([8, 9])

In [9]:
x[-3:3:-1]

array([7, 6, 5, 4])

In [10]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [11]:
np.abs(x)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
r = np.random.uniform(low=0.5, high=13.3, size=(50,))

In [15]:
np.sum(r)

322.9520699147735

In [16]:
np.prod(r)

2.65468468798824e+33

In [17]:
np.mean(r)

6.45904139829547

In [18]:
np.std(r)

4.0643446465455115

In [19]:
np.var(r)

16.51889740590316

In [20]:
np.median(r)

6.215376327480002